#ifndef SOLVER_CONSTANTS_H
#define SOLVER_CONSTANTS_H
int VERTICES,
        POINTS_IN_DOT_WAVEFRONT,
        OBSTACLES_TOTAL,
        DOTS_TOTAL,
        SENSORS;
double DX_SENSORS,
        ZERO;
float X,
        Y,
        T_MULTIPLIER,
        DT_DIGITIZATION,
        MINLEN,
        DT_DETERIORATION,
        DETERIORATION;
#endif //SOLVER_CONSTANTS_H